/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NestedRecord, Primitive, SubmitField } from "apie-form-elements/dist/types/components";
export { NestedRecord, Primitive, SubmitField } from "apie-form-elements/dist/types/components";
export namespace Components {
    interface ApieGraphiteForm {
        "initialValue"?: NestedRecord<SubmitField>;
        "internalState": NestedRecord<Primitive>;
        "polymorphicFormDefinition"?: Record<string, string>;
        "validationErrors": NestedRecord<string>;
        "value": NestedRecord<SubmitField>;
    }
    interface ApieGraphiteTest {
    }
    interface ApieGraphiteValidationError {
        "message": string;
        "valid": boolean;
    }
}
declare global {
    interface HTMLApieGraphiteFormElement extends Components.ApieGraphiteForm, HTMLStencilElement {
    }
    var HTMLApieGraphiteFormElement: {
        prototype: HTMLApieGraphiteFormElement;
        new (): HTMLApieGraphiteFormElement;
    };
    interface HTMLApieGraphiteTestElement extends Components.ApieGraphiteTest, HTMLStencilElement {
    }
    var HTMLApieGraphiteTestElement: {
        prototype: HTMLApieGraphiteTestElement;
        new (): HTMLApieGraphiteTestElement;
    };
    interface HTMLApieGraphiteValidationErrorElement extends Components.ApieGraphiteValidationError, HTMLStencilElement {
    }
    var HTMLApieGraphiteValidationErrorElement: {
        prototype: HTMLApieGraphiteValidationErrorElement;
        new (): HTMLApieGraphiteValidationErrorElement;
    };
    interface HTMLElementTagNameMap {
        "apie-graphite-form": HTMLApieGraphiteFormElement;
        "apie-graphite-test": HTMLApieGraphiteTestElement;
        "apie-graphite-validation-error": HTMLApieGraphiteValidationErrorElement;
    }
}
declare namespace LocalJSX {
    interface ApieGraphiteForm {
        "initialValue"?: NestedRecord<SubmitField>;
        "internalState"?: NestedRecord<Primitive>;
        "polymorphicFormDefinition"?: Record<string, string>;
        "validationErrors"?: NestedRecord<string>;
        "value"?: NestedRecord<SubmitField>;
    }
    interface ApieGraphiteTest {
    }
    interface ApieGraphiteValidationError {
        "message"?: string;
        "valid"?: boolean;
    }
    interface IntrinsicElements {
        "apie-graphite-form": ApieGraphiteForm;
        "apie-graphite-test": ApieGraphiteTest;
        "apie-graphite-validation-error": ApieGraphiteValidationError;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apie-graphite-form": LocalJSX.ApieGraphiteForm & JSXBase.HTMLAttributes<HTMLApieGraphiteFormElement>;
            "apie-graphite-test": LocalJSX.ApieGraphiteTest & JSXBase.HTMLAttributes<HTMLApieGraphiteTestElement>;
            "apie-graphite-validation-error": LocalJSX.ApieGraphiteValidationError & JSXBase.HTMLAttributes<HTMLApieGraphiteValidationErrorElement>;
        }
    }
}
